version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ebank-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: banckaccount
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ebank-network

  backend:
    build:
      context: ./ebanking-backend
      dockerfile: Dockerfile
    container_name: ebank-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banckaccount
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    networks:
      - ebank-network

  frontend:
    build:
      context: ./ebanking-frontend
      dockerfile: Dockerfile
    container_name: ebank-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - ebank-network

volumes:
  mysql-data:

networks:
  ebank-network:
    driver: bridge

